language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
